### ISSUE TITLE
No module named 'PandasNet'

### ISSUE THREAD

**Issue by innominate227** [fdieulle/pandasnet#1]
Getting this error on a clean install of pandasnet.

```
conda create --name test123 python=3.8
conda activate test123
pip install pandasnet
python
>>> import pandasnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\.conda\envs\test123\lib\site-packages\pandasnet\__init__.py", line 9, in <module>
    from PandasNet import Codecs
ModuleNotFoundError: No module named 'PandasNet'
```

I think this is an issue with PandasNet.dll wanting a later version of Python.Runtime.dll then the one that gets install.

If i also do
`
pip install git+https://github.com/pythonnet/pythonnet
`
which ups the version of Python.Runtime.dll it works.

**Comment by fdieulle** [comment]
The package is accessible from pip command only. I didn’t push on conda.
Try pip install pandasnet in your conda environment instead.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : ***@***.***>
Envoyé le :mercredi 28 juillet 2021 12:25
À : ***@***.***>
Cc : ***@***.***>
Objet :[fdieulle/pandasnet] No module named 'PandasNet' (#1)


Getting this error on a clean install of pandasnet.

`
conda create --name test123 python=3.8
conda activate test123
pip install pandasnet
python

import pandasnet
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\user.conda\envs\test123\lib\site-packages\pandasnet_init_.py", line 9, in
from PandasNet import Codecs
ModuleNotFoundError: No module named 'PandasNet'
`

I think this is an issue with PandasNet.dll wanting a later version of Python.Runtime.dll then the one that gets install.

If i also do
pip install git+https://github.com/pythonnet/pythonnet
which ups the version of Python.Runtime.dll it works.

**Comment by yamen** [comment]
@innominate227 is correct, I also needed to install from Github/source to get it to work. Nothing to do with conda, pip install won't work atm, Python 3.8.

**Comment by fdieulle** [comment]
The problem seems come from the official pythonnet package, which is strange because the PandasNet is bulid with netstandard2.0 and should be compatible with almost all dotnet versions since 4.x 

I failed to specify a GitHub link in the setup.py and makes it work with Travis to publish a fixed version. This issue will be fixed with the next version of pythonnet I guess. 

I don't have a better workaround than yours for now.
